### ISSUE TITLE
IOwinRequest.Schme doesn't work behind a load balancer

### ISSUE THREAD

**Issue by arkum** [AreYouFreeBusy/Amazon-OAuth-Provider#1]
I have a website which is behind a load balancer and SSL termination is happening at Load balancer. IOwinRequest.Schme returns “http” and not “https” when I access the site using https scheme. Because of this amazon returns with an error saying that the site is not whitelisted. I had to change the references to Request.Scheme to hardcoded "https" to make it work. Not sure whether there is any way to get the correct protocol scheme behind a load balancer other than forwarding the requests as SSL to each individual machine

**Comment by stefann42** [comment]
I'll do some research to see if there's a better solution other than hardcoding.

**Comment by arkum** [comment]
Sorry i forgot to update this issue with the solution i found. The fix was to check whether header contains X-Forwarded-Proto and update the owin.RequestScheme to http or https. In the startup class.

app.Use(async (environment, next) => {
    if (environment.Request.Headers["X-Forwarded-Proto"] != null) {
        environment.Set("owin.RequestScheme", environment.Request.Headers["X-Forwarded-Proto"]);
    }
    await next();
});

I don't think this should be inside the library as it is purely upto the load balancer to append this header.

**Comment by stefann42** [comment]
Got it, thanks for the tip. I'll close the issue then.
